name: 'container-deploy-active-rg'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - dockerfile
    exclude:
    - docs/README.md

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'AcrActive'
    repository: 'mycustomghost'
    command: 'buildAndPush'
    Dockerfile: '**/dockerfile'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: AzSP001
    appType: webAppContainer
    WebAppName: ghostpoc
    deployToSlotOrASE: true
    ResourceGroupName: 'active-rg'
    SlotName: dev
    DockerNamespace: ghostpocactivecr.azurecr.io
    DockerRepository: mycustomghost
    DockerImageTag: $(Build.BuildId)
    