name: 'container-deploy-active-rg'
trigger: none
pool:
  vmImage: ubuntu-latest

steps:

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'AzSP001'
    Action: 'Swap Slots'
    WebAppName: 'ghostpoc'
    ResourceGroupName: 'active-rg'
    SourceSlot: 'dev'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'AzSP001'
    Action: 'Swap Slots'
    WebAppName: 'ghostpoc-standby'
    ResourceGroupName: 'standby-rg'
    SourceSlot: 'dev'